[bastions]
bastion-01 ansible_host=3.111.218.173

[apps]
app-01 ansible_host=10.0.2.126

[ci]
ci-01 ansible_host=10.0.2.71

[bastions:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/devops-lab-2026-ssh

[apps:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/devops-lab-2026-ssh
ansible_ssh_common_args=-o ProxyJump=devops-bastion

[ci:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/devops-lab-2026-ssh
ansible_ssh_common_args=-o ProxyJump=devops-bastion
