[bastions]
bastion-01 ansible_host=3.6.86.12

[apps]
app-01 ansible_host=10.0.2.126

[bastions:vars]
ansible_user=devops
ansible_ssh_private_key_file=~/.ssh/devops-lab-2026-ssh

[apps:vars]
ansible_user=devops
ansible_ssh_private_key_file=~/.ssh/devops-lab-2026-ssh
ansible_ssh_common_args=-o ProxyJump=devops-bastion
