sonar.projectKey=devops-lab-2026-app
sonar.organization=sonarqube
sonar.host.url=http://sonarqube:9000/sonar
sonar.sources=.
sonar.language=python
sonar.python.version=3.10
sonar.coverage.exclusions=**/*
