---
- name: Check servers
  hosts: all
  become: yes

  tasks:
    - name: Check Python
      command: python3 --version
      register: python_version
      changed_when: false

    - name: Print Python version
      debug:
        msg: "{{ python_version.stdout }}"

    - name: Check Docker
      command: docker --version
      register: docker_version
      failed_when: false
      changed_when: false

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout | default('Docker not installed') }}"

    - name: Check Docker Compose
      command: docker compose version
      register: compose_version
      failed_when: false
      changed_when: false

    - name: Print Docker Compose version
      debug:
        msg: "{{ compose_version.stdout | default('Docker Compose not installed') }}"
